import type { Metadata } from "next";
import { Poppins, Geist_Mono } from "next/font/google"; // Import Poppins and Geist_Mono
import "./globals.css";

// Define Poppins font with desired weights
const poppins = Poppins({
  weight: ["400", "500", "600", "700"], // Match weights used in globals.css
  variable: "--font-sans", // Match the variable used in globals.css
  subsets: ["latin"],
  display: "swap", // Optimize font loading
});

// Keep GeistMono for --font-mono
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Online Grading and Enrollement System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}